---
app_name: "dron-ci-test"
docker:
  username: "dapmoed"
  tag: "latest"
  image: "dapmoed/{{ app_name }}"
traefik:
  api_host: "api.sloin.ru"
  api_prefix: "/{{ app_name }}"
  network: "traefik-shared"